* Mateus
** XIV

Há ao menos dois trechos sobre o mar: 1. em que Jesus dormia durante a
tempestade, e em seguida acalma o mar, 2 e. em Jesus caminha sobre o
mar e também o faz Pedro.

Notar que acontecimentos da vida de João Batista servem de sinal para
o Senhor. Quando João é preso, Jesus começa a anunciar o Reino dos
Céus. Quando Jesus sabe da morte de João, ele realize dois grandes
milagres: 1. a primeira multiplicação dos pães, e 2. caminha sobre as
águas. Ao final destes dois milagres, os discípulos exclamam pela
primeira vez: realmente tu és o filho de Deus.

A fé de Pedro durante esse capítulo fala muito sobre os homens. Pedro
acomapanhava o Senhor e havia visto muitos milagres, ele já sabia de
muitas coisas que o Senhor é capaz. Nesse ponto da história, já havia
inclusive ressuscitado a filha do centurião. Pedro então pede para que
o Senhor ordene que ele caminhe sobre as águas. Pedro então se atira
ao mar e caminha sobre ele. O momento em que pedro está prestes a sair
do barco é um grande ato de fé. Imaginá-lo me faz pensar nas pessoas
que entregam sua vida ao Senhor na confiança de que Ele proverá.

Ainda mais sobre essa passagem, mesmo depois de ter crido, Pedro tem
medo, e começa a afundar. Mesmo ele que viu tantos milagres de perto,
nesse momento, teve medo. Me parece que tal é a natureza decaída do
homem. Pentecostes ainda não havia acontecido, e sozinho Pedro não
pôde crer sem medo. E quê graça que ainda assim Pedro grita ao senhor
para que o socorra! Me parece que talvez nesse momento não foi a fé de
Pedro que vacilou, mas simplesmente que um medo surgiu em seu
coração. Talvez Pedro tivesse fé que Jesus tem todo o poder, mas não
ainda que Jesus o amava e não deixaria que ele
perecesse. Lembremos-nos, não só o Senhor pode, como virá ao nosso
auxílio. São Pedro, rogai por nós, para que tenhamos uma fé similar a
tua, e que igualmente o Senhor nos acuda quando mais precisarmos.

** XVI

Que bem aventurado foi Pedro, por ter reconhecido e anunciado pela
primeira vez que Jesus é o Cristo, o filho do Deus vivo! Em seguida
Jesus disse que não foi o sangue nem a carne que o revelou, mas o
Pai. Me pergunto se essa não e uma referência a alma (sangue), corpo
(carne), e espírito (Deus).

Há nesse capítulo uma promessa do que acontecerá no final dos tempos:
"o Filho do Homem ha de vir na glória do seu Pai, com os seus anjos, e
então retribuirá a cada um de acordo com o seu comportamento." Me
pergunto o que a Doris, que diz não acreditar em céu e inferno diria
sobre essa passagem. Há de se levar em consideração que Jesus falava
em parábolas para o povo, mas falava claramente aos apóstolos, e que
nessa cena esse dirige aos seus apóstolos.

É de se notar também a reação de Jesus quando Pedro sugere que ele não
sofra suplícios em Jerusalém: "Afasta-te de mim, Satanás!". O mestre
ensina como podemos (ou quem sabe: devemos) reagir diate das tentações
que nos afastem da vontade de Deus. Há nesse mundo quem defenda, em
nome dos interesses mundanos, o divórcio e tantos outros ataques
diretos à Lei de Deus, tão explicitamente enunciada pelo Cristo. Me
pergunto o que diriam sobre essa reação de Jesus à uma proposta tão
"razoável" (ao menos aos olhos dos homens).

"O aspectos dos céus, sabeis interpretar, mas os sinais dos tempos,
não sois capazes! Geração má e adúltera!". Me parece razoável que hoje
em 2023, mais do que nunca, o homem sabe interpretar os sinais do
céus, e ainda persistem no erro aqueles incapazes de interpretas os
sinais dos tempos. O trecho exemplifica a vontade de Deus de não
enviar sinais aos maus - pelo menos não a pedido deles, e pelo menos
não o tempo inteiro.

E quantos sinais já não havia feito Jesus! Curou e ressuscitou os
mortos, acalmou o mar e andou sobre ele, multiplicou os pães e os
peixes, expulsou demônios e ensinou com Sabedoria. E ainda assim lhe
pediam sinais vindo do Céu! Me pergunto se o sinal que pediam seria
suficiente. Se vissem no céu escrito que o filho de Deus era Jesus, e
que deveríamos segui-lo todos os Judeus, teriam mesmo crido? Ou
haveria espaço para alegarem que era bruxaria? Para alegarem que seus
discípulas faziam sinais com fumaça a distância? Para alegarem que
Jesus os havia envenenado. Diriam os modernos críticos: é uma
alucinação coletiva! E aqueles que não viram o sinal no exato instante
em que foi concedido? Teriam acredito nas palavras dos que viram? Ou
os acusariam de ter interesse próprio na questão, e de serem
imparciais? Estes homens acham mesmo que Deus tem o dever de realizar
sinais nos céus para cada um deles?

E mais: ainda que Deus enviasse os sinais, ainda que o fizesse de
forma determinística, ainda haveria espaço para a dúvida dos
incrédulos! Como sabemos disso? Pois de fato há orações infalíveis e
ainda existem os incrédulos. As orações que sempre dão resultados são
as orações insistentes feitas ao Pai pedindo por fé. Tais orações são
sempre concedidas. E fé no que? De que existe um Deus e este ama os
humanos. E mais do que disso, que ama aquela os humanos
individualmente, e não apenas coletivamente. E quantas vezes são
necessárias? Dizem os monges que 8x por dia é uma boa quantidade de
vezes para se orar pedindo fé. Mas claro, os incrédulos não estão
satisfeitos, e podem dizer que trata-se de efeito psicológico, ou
profecia auto realizável. Então é claro, poderia se sugerir que rezem
à um sapo pedindo que o sapo conceda fé ao orante, e fé no fato de que
o sapo é Deus. Ora pois, não conheço nenhum cético que tenha levado
tal método científico a prova, e por outro lado conheço histórias de
muito mártires que pediram fé, e tamanha fé lhes foi dada que
preferiram morrer à negar sua fé em Cristo.

Me parece que a mensagem é a seguinte: aos que pedem sinais, os sinais
já foram dados, e em abundância. Não é a falta de sinais que explica a
falta de fé dos homens, mas a dureza de seus corações. Aqueles que
pedem sinais devem primeiro abrir os seus corações. Sejam humildes,
reconheçam a própria pequenês, e então busquem com sinceridade a
Deus. Sigam a Lei de Deus, ofereçam sacrifícios que agradem ao Pai,
louvem-no, peçam perdão (e peçam com sinceridade, com intenção de não
voltar a ofendê-lo), peçam graças, e então, se for da vontade do Pai,
mais sinais serão enviados.

Quanto a Cristo e aos detalhes específicos da fé Católica, acredito
ser da vontade do Pai que os que buscam com sinceridade cheguem à tal
doutrina. Acredito também que se eu estiver errado sobre tal doutrina,
também será da vontade do Pai que eu encontre a verdadeira, e que eu a
encontrarei se ao menos for capaz de buscar com sinceridade cada vez
maior. E convido aqueles que acreditam terem encontrado um caminho
mais verdadeiro que o meu, que me o apresentem, pois é meu desejo
sincero trilhar o caminho mais nobre possível, e acho que seria um
erro se tal sincera vontade fosse aplicada no caminho errado, e um
tanto injusto que não houvessem meios para que um busca sincera
encontrasse o caminho.

E peço que o Cristo não veja o texto acima como um desafio ou sinal da
fraqueza da minha fé e confiança na igreja católica. Escrevo este
texto visando expor aos incrédulos a minha sinceridade na busca da
Sabedoria, na esperança de que se não forem movidos pelos meus
argumentos, sejam ao menos movidos pela minha dedicação à busca de um
caminho, e se inspirem em buscar com sinceridade, e abram então seus
corações às obras do Espírito Santo. E se meu texto for de afronta ao
Pai, peço à virgem Maria que rogue ao Pai por misericórdia. E peço a
Santo Agostinho, Santo Tomás, e ao meu anjo da guarda, que roguem para
que o Espírito Santo me infunda Sabedoria, e eu possa saber como
orientar os que estão próximos a mim. E se for da vontade do Pai que a
sabedoria só me venha pelo trabalho e estudo, peço a São José que
obtenha-me a graça de trabalhar incansavelmente em espírito de
penitência.

E ó Deus todo poderoso - digno de toda a glória pelos séculos dos
séculos, origem de tudo o que é, e mantenedor de todo o ser - que
nenhuma alma se perca por conta da minha falta de tato e de
Sabedoria. Se eu falhar, por favor enviem-lhes outros que melhor
transmitam o Evangelho. Se meu papel não for o de Sábio, ajude-me a
perceber. Se for o meu papel ser sábio, que eu o exerça quando estiver
pronto e saiba reconhecer quando estou despreparado. Tende
misericórdia de mim ó infinitamente justo Senhor, tende misericórdia
dessa homem que busca a Sabedoria, e que a beira dos 30 anos, não sabe
ainda nem como terminar esse texto.

** XVIII

Novamente encontrei um parágrado que me fez pensar na Doris. Nesse
capítulo Jesus refere-se diversas vezes ao inferno. Chama-o de o "fogo
*eterno*". E fala também da Vida e dos anjos, e da radicalidade com
que deve-se preferir entrar na Vida do que no inferno.

Também há uma passagem onde Jesus fala que o Senhor ficará mais alegre
por recuperar uma ovelha que está perdida, do que pelas 99 que estão
sãs, e também que não é da vontade do Pai que um destes pequeninos se
perca. Me parece que a passagem se relaciona diretamente com a luta
pró-vida, e contra o aborto. Se eu estiver certo sobre o que a
passagem quer dizer, ao salvar-se os pequeninos, estamos dando grande
alegria ao Pai.

Em seguida Jesus ensina como deve-se corrigir um pecador. Primeiro
conversa-se com ele em privado. Isto é, não o repreenda em
público. Depois, se necessário, levam-se outras 2 ou 3 pessoas para
falar com o pecador em particular. E por último, leva-se o pecador às
autoridades. Se nem a igreja o pecador ouvir, deve-se tratá-lo como
gentio. Me parece que aqui há um caminho que posso aplicar a minha
mãe. Já falei com ela em particular. Em seguida posso tentar levar 2
ou 3 pessoas para falar com ela. Mas quem? Quem sabe a Áurea e Tia
Damares?

E então no versículo 19 há um trecho misterioso. "se dois de vós
estiverdes de acordo na terra sobre qualquer coisa que queiram pedir,
isso lhes será concedido por meu Pai que está no céus". Isto é
curioso, pois certamente há situações de suplício que afetam várias
pessoas, e onde o suplício perdura. E há ainda o caso onde grupos de
pessoas se unem para rezar cada grupo por objetivos opostos. Como isso
pode ser entendido? Notar que Jesus diz "dois de vós". Quem sabe se
refira aos santos. Mas se esse é o caso, como entender o que vem a
seguir? "Pois onde dois ou três estiverem reunidos em meu nome, ali
estou eu no meio deles". Por que seriam necessários 2 ou 3 santos para
ter Cristo no meio deles, não bastaria um? Notar que ele fala isso
logo após falar sobre a excomunhão, e o poder de ligar e desligar, e
antes de responder a Pedro quantas vezes alguém deve ser perdoado. Me
parece que Jesus ensina aqui sobre o poder de um conselho de bispos, e
sobre como os bispos terão poder para ligar e desligar fiéis e dogmas,
mas que é necessário antes que entrem em acordo, para que um bispo só,
enganado, não desligue as coisas erradas.

Notar que os bispos tem poder de "ligar e desligar", de forma
semelhante que em filosofia clássica se diz que uma proposição liga um
sujeito à um predicado. Se a ponte entre os dois contextos for
correta, me parece que o conselho de bispos tem o poder de ligar e
desligar ideias. Dizer o que é, e o que não é. Jesus não estaria
ensinando que um conselho de bispos tem poder sobre a matéria, como em
fazer chover ou morrer e ressuscitar. E muito menos que onde qualquer
dois que digam professar a fé de Jesus Cristo terão as preces
concedidas, ou que Jesus estará no meio deles. Apesar de que, como
Deus, de fato Jesus está entre nós, mas está mesmo quando estamos
sozinhos, e mesmo entre os pecadores. Se Jesus não tem essa forma
"trivial" de estar no meio dos homens, imagino que esteja ensinando
sobre como os fiéis devem respeitar os bispos como respeitam ao
Cristo.

E há ainda de se notar que ele falava sobre bispos da magnitude dos
apóstolos - doutos no conhecimento do caminho de Deus, e virtuosos em
si mesmo. Não entendo que o Cristo quis dar carta branca a qualquer um
que em algum momento da história adquirisse o título de bispo. Por
exemplo, não entendo que o mesmo se aplicaria a Judas Escariótes, ou
aos bispos medievais que compravam seus títulos.

E por fim, o capítulo encerra com uma parábola sobre o perdão, e sobre
como Deus nos concede a misericórdia, mas espera também de nós
misericórdia, e como verá como hipocrisia aquele pecador que pede
perdão, mas não perdoa os erros de seus irmãos. Além disso, Ele é
enfático: "se cada um de vós não perdoar, *de coração*, ao seu irmão".
Ao ler isso percebo que preciso trabalhar muito em o quanto eu perdoo
meus irmãos. Por exemplo, devo perdoar os comunistas e os mega
capitalistas por suas ofensas contra mim e minha família? Contra os
ensinamentos do Pai?

Notar que na parábola, o servo devedor é punido por cobrar de um
*outro servo do mesmo senhor*. De fato, mesmo os comunistas são
criaturas de Deus. Mas assim também o é o Diabo. Devemos perdoar e
querer o bem do Diabo e dos comunistas?  Devemos fazê-lo, mesmo que
nossa inteligência nos ensine que o Diabo está no inferno, e para lá
se encaminham muitos adversários de Cristo, por vontade própria?
Seriam eles servos de Deus, mesmo que se proclamem inimigos e ajam
como inimigos de Deus?

Não encontrando resposta clara, concluo que estou na dúvida sobre esse
assunto. E o que é prudente fazer na dúvida? Perdoar em meu coração?
Manter-me afastado? Mas como ignorá-los, se a cada dia que passa noto
suas agendas avançarem sobre pessoas queridas, e sobre os ensinamentos
do Evangelho? Se os ignoro ou os perdoo, me torno inativo perante o
mal. Se os combato, corro o risco de não ter perdoado a outro
potencial servo de Deus, e me condeno da mesma forma.

Rogai por mim santos e anjos de Deus, para que minha ignorância não me
condene. Espírito Santo, enviai-me a sabedoria, e me ensina o que
fazer perante os adversários do Senhor. Santíssima Virgem Maria, rogue
por mim ó mãe, para que saiba proteger o rebanho que me foi
assinalado, e que eu não me perca ao tentar protegê-lo. Meu anjo da
guarda, proteja-me do adversário, e também da minha própria
imprudência. E se for da vontade do Pai que eu adquira o conhecimento
por meio do trabalho e do estudo, rogai por mim São José, pela graça
de trabalhar em espírito de penitência.

* COMMENT Local variables
# local variables:
# display-line-numbers-width: 3
# ispell-local-dictionary: "brasileiro"
# end:

#+begin_src elisp
(ispell-change-dictionary "brasileiro")
(ispell-buffer)
(setq ispell-local-dictionary "brasileiro")
#+end_src
