* <2023-02-13 seg> Primo, você gosta dessa música?

Um primo me envia : [[https://www.youtube.com/watch?v=khdH-heeojU][este link]], e me pergunta se gostei da música. O
que dizer?

Tendo crescido em um mundo predominantemente pagão, e falhado em me
livrar das influências passadas, eu confesso que o aspecto geral da
música me é agradável de ouvir. Se eu estivesse em um bar e começasse
a tocar a música do Teddy Swims, eu, desprevenido, começaria a beter o
pé no ritmo da música. Entretanto, parando para ver o vídeo e ler a
letra, descubro que tenho diversos problemas com essa música. De fato,
são tantos problemas que vejo que é difícil saber por onde começar.

Mas claro, antes de dizer algo, me mandou a prudência, que no espírito
de não espantar o paciente, perguntei ao meu primo se ele gosta da
música, e ele disse que gosta, e que é eclético. Ora, eu respondo
então que batida é boa, mas não é minha praia. E ficaria por isso, não
fossem as ideias remoendo em minha cabeça, e na necessidade de pô-las
em ordem, resolvi escrever esse texto.

Para começar noto no artista o aspecto de gordo amigo de todos,
vestindo um poncho, e usando um brinco que já seria exagerado se fosse
na orelha de um índio. Suas unhas estão pintadas de preto, e em sua
testa está tatuado "paciência". Nesse ponto já temo, pelo conjunto da
obra, que o artista vai reverberar os valores do politicamente
correto, e irá atacar tudo o que há de belo, bom, e verdadeiro. Mas
como meu primo gostou, mantenho a esperança de que a coisa pode ser
boa.

A música começa com um solo de "uuuhuuus", o que me evoca que algo
profundo está por vir. Penso "oras, meu primo é evangélico, quem sabe
não vem por aí uma música sobre o imaterial e a graça da redenção". Os
músicos que acompanham o cantos são todos negros, quem sabe não vem de
origem humilde e foram ensinados pela piedade dos evangélicos.

Eis então a primeira frase "baby you just don't get it". Percebo então
que se trata de uma música sobre romance. E aqui já encontro um
erro. Se a música seguir por onde acho que vai, a música não louva o
senhor, não pede perdão, não pede por graças ou misericórdia, nem
agradece ao Senhor. Me parece que não é o tipo de coisa que eu quero
aprender e ficar lembrando de forma inconsiente ao longo dos dias.

Mas bom, vamos lá, não é uma música piedosa. Talvez seja uma música
neutra aos planos de Deus, se é que tal coisa exista. Quem sabe é algo
que eu possa ouvir sem ter que criticar. Prossigamos.

#+begin_quote
Do you enjoy being hurt?
I know you smelled the perfume, the make-up on his shirt
You don't believe his stories
You know that they're all lies
Bad as you are, you stick around and I just don't know why
#+end_quote

Exatamente o que eu temia. O gordo-amigo-de-todos acredita que sua
amada está erroneamente se envolvendo com os homens errados, e que
ele, o gordo simpático, é o homem certo.

#+begin_quote
If I was ya man (baby, you)
Never worry bout (what I do)
I'd be coming home (back to you)
Every night, doin' you right
You're the type of woman (deserves good thangs)
Fistful of diamonds (hand full of rings)
Baby, you're a star (I just want to show you, you are)
#+end_quote

Teddy segue então a descrever como ele é o homem que irá valorizar
adequadamente a mulher amada, que ele voltaria todos os dias para
casa, e que ela nunca teria que se preocupar com ele. Todas essas
coisas parecem até boas, mas Teddy parece não estar consciente de uma
estratégia mais eficaz: se tornar um homem virtuoso.

Teddy parece não entender a realidade de como as mulheres
funcionam. Elas procuram o homem de maior valor que conseguirem
atrair, e elas prefeririam ficar sozinhas, a ficarem com um homem de
baixo valor. Se a mulher for piedosa, procurará por fé, esperança, e
caridade, mas ainda que não seja, procurará pelas virtudes da
fortaleza, temperança, justiça, e prudência, ou outra forma menor de
virtude. É bem verdade que muitas mulheres modernas confundem os
sinais pelas coisas, de modo que podem achar que um homem atlético é
um homem dotado da fortaleza e perseverança, mas recomendaria ao Teddy
que também não desejasse uma mulher que faça tamanha confusão.

Digo tudo isso porque Teddy está tremendamente enganado. As mulheres
sabem que homens virtuosos se envolvem com grandes projetos, e que
grandes projetos requerem mais horas do que há em um dia, de forma que
estar sempre com a mulher, tentando sempre satisfazê-la é um sinal
oposto do que a mulher busca: é um sinal de que o homem não está
envolvido com projetos grandes o suficiente, de que não é virtuoso o
suficiente, pois depois de um certo nível elementar, a virtude se
conquista com grandes obras.

Em resumo: a mulher irá preferir o risco de estarem distantes de seus
esposos virtuosos, do que a certeza de estar com um parceiro sem
culhões.

Mas há ainda nesse trecho um outro problema. Teddy cobriria sua mulher
de diamantes. Ora, Teddy é materialista. Se por um lado ele quer ser
apreciado pelas suas qualidades imateriais, por outro, ele mostra o
seu apreço com pedras preciosas. Imagino quão surpreso Teddy ficaria,
ao perceber que mulheres que se interessam por diamantes,
frequentemente se interessam pela forma física de um homem, e que se
ela se intessa pelo material mais duro encontrado na Terra,
dificilmente se interessaria pela bunda mole de Teddy. Se eu
conhecesse Teddy, gostaria de lhe recomendar que não busque quem se
atrai por coisas que ele não pode oferecer.

Destaco a seguir o que acredito ser o pior erro de Teddy:

#+begin_quote
You should let me love you
Make me your selection
Show you the way love's supposed to be
Baby, you should let me love you, love you, love you
#+end_quote

Teddy acredita estar no direito de dizer o que os outros deveriam
amar. Ora Teddy, ao homem somente é lícito orientar a própria
vontade. Pela razão dois escravos da verdade podem obrigar um ao outro
a concordarem em algo, mas quanto ao amor, que está dentro da esfera
da vontade, nos limitamos a orientar o nosso próprio.

#+begin_quote
Your true beauty's description looks so good that it hurts
You're a dime plus ninety-nine and it's a shame
Don't even know what you're worth
Everywhere you go they stop and stare
'Cause you're bad and it shows
From your head to your toes, out of control, baby you know
#+end_quote

Teddy está atraído por uma espécie de mulher que todos param para
olhar. Interpreto pelo conjunto da obra, que as pessoas parem para
apreciar a beleza física de sua amada, o que pouco nos diz sobre suas
virtudes. Até um certo ponto me parece natural buscar a belo, mas
espero que Teddy reconheça que nem tudo que brilha é ouro, que a
abelha que se guia pelo olfato pode acabar nos dentes de uma planta
carnívora, e que as aparências podem enganar. Oremos para que Teddy
considere em sua avaliação as virtudes de sua amada, e em sua próxima
música nos conte sobre sua virtuosa parceira.

Mas eu me enganei. O problema piora a seguir, e Teddy se propõe a uma
missão impossível:

#+begin_quote
Let me be the one to give you everything you want and need
#+end_quote

Teddy não tem ciência de que mortal algum pode satisfazer uma mulher
(e nenhuma mortal a nenhum homem), e que somente o Cristo é capaz de
nos trazer felicidade plena e durável. Teddy possui uma visão
antropológica que apenas o trará frustrações. Ainda que Teddy
conseguisse sua amada, ele se frustraria em satisfazê-la. Ele notaria
que 2~3 anos depois de se juntarem, ela perdeu o interesse pelas
coisas bonitas que ele traz.

Ele mesmo perderia o interesse nela, e se perguntaria por que não sair
com outras garotas, quem sabe mais jovens e mais bonitas. Isso se ele
não se perguntasse se a real felicidade se encontra em sair com outros
homens, ou quem sabe outros casais - tudo vale, ao menos segundo a
opinião de muitos intelectuais modernos. E Teddy já tem as unhas
pintadas de preto, o que é meio caminho andado para ser aceito nas
mais variadas comunidades LGBTQIA+.

Teddy jamais encontraria a felicidade duradoura que busca nas outras
pessoas, ou que pretende levar às outras pessoas, e então poderia se
perguntar se o problema não era com ele mesmo, ponto em que Teddy se
envolveria com remédios e drogas que o deixassem quimicamente
alegre. Mas tal é a natureza do homem, e tão profunda a sabedoria do
projeto de Deus, que não há na Terra substância que mantenha o homem
satisfeito por tempo suficiente. E enfim Teddy, se sobrevivesse a essa
experiência, se frustraria. Tudo porque buscou satisfazer com coisas
mundanas algo que só pode ser satisfeito com o divino.

E claro, Teddy é apenas um artista. É possível que ele exponha as
ideias das massas, sem que ele mesmo as tome para si. Entretanto, se
esse é o caso, as minhas preocupações são para com as massas, e se
tornam então ampliadas numericamente.

Antes de encerrar, acho preciso deixar claro que Teddy ser gordo, em
si, não é problema algum. Se realcei essa característica de Teddy, foi
para apontar o padrão duplo com que ele avalia e com o qual espera ser
avaliado. Além disso, o aspecto amigo-de-todos não é em si um
mal. Ataco apenas o uso de tal atitude como substituto da
virtuosidade.

** Removido

Noto porém que já nessa primeira frase há algo esquisito: "baby you
don't get it". Uma frase de uma música romântica começa por declarar
que a coisa amada não entende a situação. De fato, as vezes é o caso.
Por exemlo, os pais amam os filhos, e tambem sabem de coisas que os
filhos não entendem. Mas há algo de esquisito em assumir relação
similar entre um homem e sua pretendente.

* <2023-02-13 seg> O que dizer a um folião

Tem me ocorrido, durante os últimos dias, que o Carnaval pode ser uma
chance de conversão para muitos pecadores.

Ora mas como? Durante o Carnaval as pessoas estão mais abertas, e
estão concentradas em um lugar só. Se há um bom lugar para se anunciar
a todos os jovens de uma região, este lugar é o carnaval.

Não que a tarefa seja fácil. As festas de Carnaval são verdadeiros
lugar de exaltação das paixões e dos pecados. O jovem folião quer
saber de tudo, menos de santidade. Mas veja que não preciso torná-lo
um santo durante o carnaval, mas apenas plantar dúvidas sobre o seu
estilo de vida.

Quantos porres precisará um folião tomar para entender que alegria que
ele encontra no fundo da garrafa é passageira? Com quantos homens
precisará uma jovem solteira antes de sentir-se ferida pelas
aventuras?

Não proponho aqui uma pregação no estilo de "arrependam-se pois o fim
está próximo", mas um tom de "alegrem-se pois a felicidade plena é
possível".

Seria factível que um evangelista, carregando copos de água e
panfletos com pequenas mensagens, conseguisse tocar o coração de
alguns jovens? Quais seriam as mensagens? Como se vestiria o apóstolo?
Iria sozinho ou em grupo? Essas são perguntas que me pego pensando.

** Penitência em preparação para a missão

Um homem disposto a seguir tal apostolado precisaria estar
preparado. Em muitos aspectos, a missão se assemelha a entrar as
portas do inferno e resgatar algumas pobres almas. Os demônios estarão
de olho, e sedentos por uma alma em estado de graça.

Eu recomendaria que tal homem fizesse muito jejum antes da batalha. Ao
menos durante a última semana antes do confronto. Recomendaria que se
confessasse antes da jornada, e frequentasse missa todos os dias dessa
semana. E que rezasse também o terço pedindo a proteção de Maria para
vencer o pecado, assim como coroas ao Arcanjo Miguel.

** Ir acompanhado

Recomendaria que o missionário fosse acompanhado. É simplesmente muito
arriscado sair em missão sozinho. Mesmo sem influência direta de
demônios, é fácil prever, por exemplo, um possível linchamento por
meio de grupos de feministas.

** Vestir uma roupa de peregrino?

Enquanto por um lado o carnaval parece uma boa chance de se vestir
como um franciscano, por outro, pode dar muito na cara para os
adversários. E lembre-se, o jovem missionário estaria cercado. Como se
esconder na multidão em caso de linchamento?

Eu recomendaria roupas normais. Como de quem vai ao shopping. O mais
neutras possíveis. Um boné e outros itens de vestimenta que pudessem
ser descartado em caso de fuga.

** Quais mensagens entregar?

Seria importante manter o foco: a missão trata-se de plantar sementes
no coração dos pecadores. Nada muito avançado. Lembre-se: leite para
crianças. E também: não jogue pérolas aos porcos ou aos cães.

Me parece que aos bêbados, um copo d'água, uma conversa rápida sobre o
assunto que convir, e uma pergunta: quantas vezes você se embriagou, e
quantas precisará se embriagar para ser realmente feliz?

À jovens, um comentário sobre algum cara babaca fazendo babaquice, e
uma pergunta: não tens medo de aqui acabarás se envolvendo com um
babaca? Ou então, imagina descobrir no dia seguinte, que você dormiu
com um babaca?

Aos membros da comunidade LGBT, uma pergunta sincera: a sua nova
identidade satisfez mesmo os seus anseios? É tudo maravilha depois de
se assumir, ou sobram questões existenciais que sempre estiveram lá
dentro?

Fora isso, atos de caridade deixarão a sua marca: oferecer água, ou
para tirar fotos, ou avisar alguém de uma carteira perdida, ou se um
ladrão que se aproxima.

Quem sabe levar uma câmera profissional, bater fotos, elogiar as
pessoas e comentar "uau, que sorriso bonito, você me lembra a minha
mãe". Ou "que casal bonito, vocês dariam uma bela família". Algo nesse
sentido. Pessoas adoram fotógrafos de festa.

Outra opção seria vender bebida na festa. E nos poucos momentos de
contato com o comprador, falar sobre um dos assuntos acima. "Deus
deveria estar inspirado quando te criou".

** E se houvesse um panfleto, qual  mensagem gostaria de deixar para o folião genérico?

- Algum desafio que sugira alguma das 5 provas:
    * Já pensou o que o mantém na existência a cada instante? Como
      poderia o movimento desordenado de átomos produzir a cada
      instante você um ser que pensa e põe ordem nas coisas?
    * Você é mais do que um cachorro. Hábitos, alimentos e
      medicamentos, recompensas e punições: é assim que se treina um
      cachorro. O que te faz diferente de um cão?
    * Em 10 anos todas as células do seu corpo terão se trocado. O que
      terá se mantido o mesmo? O que é você realmente?
- Há um caminho para a felicidade duradoura
- Esse caminho requer que você primeiro dome os desejos do corpo
- Em seguida, passa-se a escutar os caminhos do espírito
- Siga com sinceridade o que o espírito te indicar e busque com
  sinceridade propósito e a origem dos ensinamentos
- Você pode ignorar os caminhos do espírito, mas nada o satisfará nem
  duradouramente nem plenamente. Quando tiveres percebido isso na
  prática, antes de desistir de tudo, ou então antes de entrar em
  remédios, lembre-se que há o caminho do espírito a ser trilhado.
- Você sabe que há algo de errado com o mundo. Abafe as paixões dos
  sentidos, siga com sinceridade o que te diz o espírito, e descubra o
  que está errado.
- Atente-se para os adversários. Como você está perdido, assim também
  estão muitos outros, e há lobos em busca de homens perdidos.
- Como saber quais os lobos e quais os pastores? Pelas obras
  distinguireis os bons dos maus. Isto é: pelos resultados dos que o
  seguem. Mas busque atentamente os resultados. O lobos sabem disso, e
  vão tentar te vender gato por lebre. E eles são bons marketeiros.
- O caminho para a felicidade passa por sacrifícios pessoais
  intensos. Se estão te vendendo apenas conforto, provavelmente você
  está falando com um dos lobos.
- Escute atentamente ao seu espírito. Se você for sincero, notarás
  algo se retorcendo dentro de ti toda vez que cometes um crime contra
  o espírito.
- Não importa o quanto você errou, se fores capaz de se arrepender
  profundamente, Deus o perdoará, e a caminho para a felicidade lhe
  será aberto.
- Desconfie de qualquer um que te diga que não há propósito para a
  vida, ou que é tudo aleatório, ou questão de poder, ou de dinheiro,
  ou que não há nada sagrado. Escrito no seu próprio ser estão as
  verdades que dizem que há um propósito, e há também verdades que não
  se podem opor com honestidade, e que há o sagrado, e que o sagrado é
  superior ao profano. Dentro de ti há uma luz superior a todo o mundo
  material. Desconfie dos que querem apagá-la.

Acredito que uma combinação das mensagens acima poderia ser
distribuída no formato de biscoitos da sorte ou algo do gênero.

* <2023-02-14 ter> Orações aos santos

Não foi a primeira vez que escutei críticas às devoções aos
santos. Disse minha amiga que os santos fazem milagres procurando
atrair para si a atenção que é devida a Deus. Curiosamente essa mesma
amiga tem em sua casa altares para Budda e Iemanjá, e nisso não vê
problemas, mas para os homens e mulheres que foram radicais na sua
imitação ao Cristo, segundo o ataque, esses são adversários do Pai!
Como justificar a devoção aos santos?

Em primeiro lugar é preciso dizer que as devoções aos Santos são
devoções a Deus, pois os Santos são obra prima de Deus, e assim como
um artista fica feliz quando o público gosta de suas obras, Deus fica
feliz quando os homens notam a extraordinariedade de Seus Santos.

É claro que existem devotos que se passam, e é claro que quem vê de
fora pode não entender o que se passa na cabeça do fiel. De qualquer
forma, é fato registrado que o ensinamento da Igreja sobre os santos é
claro: os Santos estão próximos de Deus e podem rogar a Ele pelos
fiéis. Todo o poder vem de Deus, e o santo em si é um intermediário. E
só se torna santo imitando-se o Cristo. Os Santos são lembretes que
recebemos de tempos em tempos das virtudes do Cristo, e do quão
intensamente podemos amá-lo. Devoção aos Santos é devoção ao Pai, ao
Filho, e ao Espírito Santo, pois também os santos são devotos destes.

Também ensina a Igreja que santos são aqueles fiéis que após a morte
vão direto para o céu. Isto é: não passam pelo purgatório. Com isso em
mente, existem muito mais santos do que conhecemos, e os santos que
conhecemos, os conhecemos pois sua entrega foi tão radical que Deus
quis que milagres acontecessem ao redor do Santo. De forma que a
Igreja toma os milagres como evidência de santidade, e reconhece
devoção legítima ao Santo. Eu entendo os milagres como uma forma de
Deus dizer: "este meu filho, este entendeu minha mensagem. Prestem
atenção no que ele fez, e façam de forma similar, e assim me
agradarão".

Ainda com a definição anterior em mente, pode-se responder a um
questionamento comum: por que não vemos mais santos por aí? Ora, eu
entendo que podem haver vários santos ao nosso redor, e que se não os
vemos é pela dureza dos nossos corações. O que faz o Santo é a sua
entrega às Obras de Deus, e não os milagres, e como nossos corações
endurecidos pedem milagres espantosos, acabamos por achar que não mais
santos. E mais: se muitos judeus não puderam reconhecer o próprio
Cristo, assim também nós, que vivemos em um mundo muito menos devoto
que a Judeia e Galileia em que Cristo ensinou, não somos capazes de
reconhecer os santos que Deus nos envia. O que já disse dos incrédulos
do passado, digo para nós mesmos: há muitos que viram milagres e não
acreditaram, e não é de se surpreender que Deus utilize de outros
meios para ensinar o homem, que não os milagres.

Há outros dois argumentos que recebo com frequência: 1. não disse
Cristo somente por meio dele se chega ao Pai (ou que entre Deus e o
homem só há o Cristo como intercessor), e 2. qual a diferença entre os
Santos e os ídolos de outras religiões (como Budda e Iemanjá)? Não
poderiam estes serem santos enviados aos povos pagãos?

Responderei primeiro à segunda pergunta.

* COMMENT Code

# local variables:
# display-line-numbers-width: 3
# ispell-local-dictionary: "brasileiro"
# end:

#+begin_src elisp
(ispell-change-dictionary "brasileiro")
(ispell-buffer)
(setq ispell-local-dictionary "brasileiro")
#+end_src
